In [1]:
import numpy as np

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[84,  3],
       [44, 49],
       [79, 28],
       [70, 65],
       [82, 79],
       [24,  4],
       [ 0, 52],
       [39, 84],
       [58, 51],
       [73, 60]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

C:\Users\Chris\Anaconda3\envs\tfdeeplearning\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scaler_model.transform(data)

array([[ 1.        ,  0.        ],
       [ 0.52380952,  0.56790123],
       [ 0.94047619,  0.30864198],
       [ 0.83333333,  0.7654321 ],
       [ 0.97619048,  0.9382716 ],
       [ 0.28571429,  0.01234568],
       [ 0.        ,  0.60493827],
       [ 0.46428571,  1.        ],
       [ 0.69047619,  0.59259259],
       [ 0.86904762,  0.7037037 ]])

In [11]:
import pandas as pd

In [13]:
mydata = np.random.randint(0,101,(50,4))

In [14]:
mydata

array([[20, 59, 69,  9],
       [53, 84, 11, 97],
       [98, 39, 47, 14],
       [47, 11, 98, 80],
       [39, 55, 82, 71],
       [65, 63, 65, 40],
       [71, 75, 22, 88],
       [45, 77, 38,  4],
       [78, 80, 44, 33],
       [60, 49, 64, 58],
       [55, 76, 89, 40],
       [47, 13, 70, 39],
       [ 2, 99, 53, 24],
       [81, 74, 40, 24],
       [22, 97, 66, 70],
       [52, 55, 81, 83],
       [41, 13, 40, 37],
       [ 6, 86, 98, 12],
       [13,  6, 86, 81],
       [ 6, 19, 66, 25],
       [66, 78, 71, 91],
       [89, 43, 89, 75],
       [27, 14, 91, 53],
       [18, 36, 31,  4],
       [81, 66, 90, 35],
       [50, 12, 46, 93],
       [54, 18, 74, 53],
       [31, 78, 85, 70],
       [94, 38, 46, 87],
       [50, 57, 27, 46],
       [34, 83, 37, 31],
       [35, 89, 85, 55],
       [75,  8,  2, 10],
       [ 2, 76, 11, 77],
       [51, 30, 81, 91],
       [62, 18, 52, 13],
       [95,  8, 93, 60],
       [58, 42, 81, 34],
       [93, 37,  8, 18],
       [99, 43, 48, 32],


In [19]:
df = pd.DataFrame(data=mydata, columns= ['f1','f2','f3','label'])

In [20]:
df

f1  f2  f3  label
0   20  59  69      9
1   53  84  11     97
2   98  39  47     14
3   47  11  98     80
4   39  55  82     71
5   65  63  65     40
6   71  75  22     88
7   45  77  38      4
8   78  80  44     33
9   60  49  64     58
10  55  76  89     40
11  47  13  70     39
12   2  99  53     24
13  81  74  40     24
14  22  97  66     70
15  52  55  81     83
16  41  13  40     37
17   6  86  98     12
18  13   6  86     81
19   6  19  66     25
20  66  78  71     91
21  89  43  89     75
22  27  14  91     53
23  18  36  31      4
24  81  66  90     35
25  50  12  46     93
26  54  18  74     53
27  31  78  85     70
28  94  38  46     87
29  50  57  27     46
30  34  83  37     31
31  35  89  85     55
32  75   8   2     10
33   2  76  11     77
34  51  30  81     91
35  62  18  52     13
36  95   8  93     60
37  58  42  81     34
38  93  37   8     18
39  99  43  48     32
40   8  91   5     23
41  96  32  16     67
42  68   2  15     57
43   1  80  43     45
44  88  30   2     15
45  80  73  72     74
46  59  58  85     36
47  63  71   9     82
48  58  10  40     90
49  64  23  19     24

In [22]:
X = df[['f1','f2','f3']] # features

In [24]:
y = df['label'] #label

In [25]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [31]:
X_train.shape

(35, 3)

In [32]:
X_test.shape

(15, 3)