In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [17]:
fill_mat = tf.fill((4,4),10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [22]:
myrandu = tf.random_uniform((4,4), 0, 1)

In [23]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [24]:
sess = tf.InteractiveSession() # cells below act as if inside tf.session()

In [26]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 1.72454607 -0.46688253 -0.01345992  1.43423557]
 [ 2.10689855 -0.00296833  1.0863086   1.58834052]
 [-0.50547183 -0.18151268 -0.73159397 -0.29802215]
 [ 0.26609436 -0.71308613 -0.57237774 -1.41584563]]


[[ 0.36545897  0.87136436  0.82289982  0.54909801]
 [ 0.75034082  0.44747913  0.24262559  0.321172  ]
 [ 0.98194408  0.99696219  0.38914156  0.70358551]
 [ 0.62559116  0.57849109  0.26873267  0.42416215]]




In [28]:
a = tf.constant([[1,2],
               [3,4]])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [31]:
b = tf.constant([[10],[100]])

In [32]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [33]:
result = tf.matmul(a,b)

In [36]:
sess.run(result)

array([[210],
       [430]])